ALTER TABLE `user` ADD `created_at` INT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `user_experience` ADD `created_at` INT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `emotion` ADD `created_at` INT NOT NULL DEFAULT CURRENT_TIMESTAMP;
